server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
  application:
    name: USER-SERVICE
          
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   